### PR TITLE
Support NDI

### PR DESCRIPTION
**Pull request by fand**
This PR adds NDI command to ZIG SIM Plus.
Most code is under the private repository.

### CODE REVIEW

**Comment by nozomuplus** [comment]
File hierarchy in the project should be reconsidered.
Some files in the "ZIGSIMPlus" are not related to the fundamental structure, and they should be moved into some folder beneath.

Besides, NdiMonitoringCommand.start is not used.
Protocol structure should be reconsidered.

**Comment by fand** [comment]
I reorganized the file structure.
Now NDI related files are located in `$(SRCROOT)/Frameworks/Private`.

> Besides, NdiMonitoringCommand.start is not used.
> Protocol structure should be reconsidered.

`NdiMonitoringCommand.start` is not used but required to satisfy `Command` protocol.
We can add another layer of protocol to make `start` optional like following picture, but it's too complicated for this situation, in my opinion.

image

**Comment by nozomuplus** [comment]
File structure is well-organized!

> Anyways, I fixed NdiMonitoringCommand.start to print error on the log that it should be never called.

In this case, `fatalError` or `assert` is commonly used.
See https://scior.hatenablog.com/entry/2019/04/04/202352

**Comment by fand** [comment]
OK, I replaced `print()` with `assertionFailure()`.
Also I merged master branch again and tested on my PC.

**Pull request merged**
